name: Deploy Blog

on:
  workflow_dispatch:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: |
          pnpm deps
          pnpm build
      
      - name: Deploy
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}