name: Deploy Blog

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: |
          pnpm deps
          pnpm build
      
      - name: Commit and push if it changed
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<contact@jeroenpeeters.be>"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: deploy"
          git push

      - name: Show blog URL in summary
        run: |
          echo "Deployed to: [https://jeroenpeeters.be](https://jeroenpeeters.be)" >> $GITHUB_STEP_SUMMARY