name: Preview Deploy Blog

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - run: |
          pnpm deps
          pnpm build:dev
      
      - name: Deploy to Surge
        run: |
          npm i -g surge
          surge ./docs jeroenptrs-preview.surge.sh --token ${{ secrets.SURGE_TOKEN }}
      
      - name: Show Surge URL in summary
        run: |
          echo "Deployed to: [https://jeroenptrs-preview.surge.sh](https://jeroenptrs-preview.surge.sh)" >> $GITHUB_STEP_SUMMARY